### ISSUE TITLE
What dataset？

### ISSUE THREAD

**Issue by bityangke** [qijiezhao/Video-Highlights-Detection#1]
Hi Qijie
What dataset you used in your experiments?

**Comment by qijiezhao** [comment]
tvsum or summe

**Comment by qijiezhao** [comment]
However, my experiment is far away from enough solid, this repo is a tiny schedule to push myself : )

**Comment by bityangke** [comment]
Thanks very much, you may try the Video Highlights dataset released by [baidu ai](http://ai.baidu.com/broad/introduction)

**Comment by bityangke** [comment]
Sorry , I have not noticed that you have already use this dataset.
